// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ad9aRODnVrCTYf88MApYDmfR7TpJbRE',
    appId: '1:338216089950:web:5fd6e3f2a81ad077d6f7cf',
    messagingSenderId: '338216089950',
    projectId: 'vonjiaina-geit',
    authDomain: 'vonjiaina-geit.firebaseapp.com',
    storageBucket: 'vonjiaina-geit.firebasestorage.app',
    measurementId: 'G-GH7SD6EESS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAJ8mnjdKIw56cwJVbwZjZ8yNmfAV_OXg',
    appId: '1:338216089950:android:3f0ef9e2b0665fa4d6f7cf',
    messagingSenderId: '338216089950',
    projectId: 'vonjiaina-geit',
    storageBucket: 'vonjiaina-geit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkYukr5aRlFuKWFJryeBeiiBRst7CQ_Vg',
    appId: '1:338216089950:ios:86b5bcb522ec3a02d6f7cf',
    messagingSenderId: '338216089950',
    projectId: 'vonjiaina-geit',
    storageBucket: 'vonjiaina-geit.firebasestorage.app',
    iosBundleId: 'com.example.vonjiainaFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkYukr5aRlFuKWFJryeBeiiBRst7CQ_Vg',
    appId: '1:338216089950:ios:86b5bcb522ec3a02d6f7cf',
    messagingSenderId: '338216089950',
    projectId: 'vonjiaina-geit',
    storageBucket: 'vonjiaina-geit.firebasestorage.app',
    iosBundleId: 'com.example.vonjiainaFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ad9aRODnVrCTYf88MApYDmfR7TpJbRE',
    appId: '1:338216089950:web:f0c17a37991b1603d6f7cf',
    messagingSenderId: '338216089950',
    projectId: 'vonjiaina-geit',
    authDomain: 'vonjiaina-geit.firebaseapp.com',
    storageBucket: 'vonjiaina-geit.firebasestorage.app',
    measurementId: 'G-CMD5HGEEMK',
  );
}
